In [5]:
import numpy as np

# Функция для QR-разложения с использованием метода отражений Хаусхолдера
def qr_decomposition(A):
    n, m = A.shape
    Q = np.eye(n)
    R = A.copy()
    print(A)

    for i in range(min(n, m)):
        # Вектор отражения Хаусхолдера
        x = R[i:, i]
        e = np.zeros_like(x)
        e[0] = np.copysign(np.linalg.norm(x), -A[i, i])
        u = x - e
        norm_u = np.linalg.norm(u)
        
        # Избегаем деления на 0
        if norm_u != 0:
            v = u / norm_u
        else:
            v = u

        # Отражение R
        R[i:, i:] -= 2.0 * np.outer(v, np.dot(v.T, R[i:, i:]))
        # Отражение Q
        Q[i:] -= 2.0 * np.outer(v, np.dot(v.T, Q[i:]))

    return Q.T, R

# Функция QR-алгоритма для поиска собственных значений
def qr_algorithm(A, iterations=1000):
    # Преобразуем матрицу A к типу float
    A = A.astype(float)
    
    n, m = A.shape
    Ak = A.copy()
    for _ in range(iterations):
        Q, R = qr_decomposition(Ak)
        Ak = R @ Q  # Обновляем матрицу на RQ
    eigenvalues = np.diag(Ak)  # Собственные значения на диагонали
    return eigenvalues

# Пример матрицы
A = np.array([[4, 1], [2, 3]])
eigenvalues = qr_algorithm(A)
print("Собственные значения матрицы A:", eigenvalues)



[[4. 1.]
 [2. 3.]]
[[5.00000000e+00 4.53932125e-17]
 [1.00000000e+00 2.00000000e+00]]
[[ 5.07692308 -0.61538462]
 [ 0.38461538  1.92307692]]
[[ 5.04154303 -0.85163205]
 [ 0.14836795  1.95845697]]
[[ 5.01819666 -0.94167736]
 [ 0.05832264  1.98180334]]
[[ 5.00752141 -0.97684295]
 [ 0.02315705  1.99247859]]
[[ 5.00304675 -0.99076518]
 [ 0.00923482  1.99695325]]
[[ 5.00122477e+00 -9.96310584e-01]
 [ 3.68941618e-03  1.99877523e+00]]
[[ 5.00049088e+00 -9.98524957e-01]
 [ 1.47504295e-03  1.99950912e+00]]
[[ 5.00019650e+00 -9.99410099e-01]
 [ 5.89901294e-04  1.99980350e+00]]
[[ 5.00007863e+00 -9.99764058e-01]
 [ 2.35941969e-04  1.99992137e+00]]
[[ 5.00003145e+00 -9.99905626e-01]
 [ 9.43738191e-05  1.99996855e+00]]
[[ 5.00001258e+00 -9.99962251e-01]
 [ 3.77490527e-05  1.99998742e+00]]
[[ 5.00000503e+00 -9.99984900e-01]
 [ 1.50995451e-05  1.99999497e+00]]
[[ 5.00000201e+00 -9.99993960e-01]
 [ 6.03980587e-06  1.99999799e+00]]
[[ 5.00000081e+00 -9.99997584e-01]
 [ 2.41592040e-06  1.99999919e+00]]
